version: '3.9'

services:
  # Mongodb container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 4000
      MONGO_DB_URI: mongodb://mongo_db:27017
      DB_NAME: GatewayDb
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
